apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cla-ingress-svcl8tr
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  tls:
  rules:
